name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  push-container:
    runs-on: ubuntu-latest # run on hosted runner, because it's a public repo

    steps:
      - uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/zeitonline/gh-action-gke-deployer:${{ github.ref_name }}
            ghcr.io/zeitonline/gh-action-gke-deployer:v0
            ghcr.io/zeitonline/gh-action-gke-deployer:latest
